-- CreateEnum
CREATE TYPE "UserPersona" AS ENUM ('DESIGNER', 'FABRIC_SUPPLIER', 'SAMPLE_STUDIO', 'FACTORY', 'BUYER', 'CONSUMER', 'TEACHER', 'SCHOOL', 'OTHER');

-- AlterTable
ALTER TABLE "User" ADD COLUMN "persona" "UserPersona" NOT NULL DEFAULT 'CONSUMER',
ADD COLUMN "personaCompleted" BOOLEAN NOT NULL DEFAULT false;
