import * as assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const report = readFileSync("RUNWAYLAB_OPERATIONAL_ACCEPTANCE_V2_0B_4_2_5_REPORT.md", "utf8");
const checklist = readFileSync("RUNWAYLAB_V2_0B_4_2_5_PRODUCTION_ACCEPTANCE_CHECKLIST.md", "utf8");
const packageJsonText = readFileSync("package.json", "utf8");
const playwrightConfig = readFileSync("playwright.config.mjs", "utf8");
const e2eSpec = readFileSync("e2e/operational-acceptance.spec.mjs", "utf8");
const packageJson = JSON.parse(packageJsonText) as {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
};

assert.match(report, /E2E 覆盖/, "report should keep P1-03 as a real E2E coverage concern");
assert.match(report, /Prisma 数据库断言/, "report should document database assertions");
assert.match(checklist, /用户提交行动结果/, "E2E plan should cover user action result submission");
assert.match(checklist, /管理员接受并转换/, "E2E plan should cover admin acceptance and conversion");
assert.match(checklist, /并发创建当前行动/, "E2E plan should cover concurrent current action creation");
assert.match(checklist, /推荐 E2E 场景/, "production checklist should keep an E2E section");
assert.match(checklist, /隔离测试数据库/, "production checklist should require an isolated test database");

assert.ok(packageJson.devDependencies?.["@playwright/test"], "@playwright/test must be a devDependency");
assert.equal(packageJson.dependencies?.["@playwright/test"], undefined, "@playwright/test must not be a runtime dependency");
assert.match(playwrightConfig, /const host = "127\.0\.0\.1";/, "Playwright config should keep the fixed local E2E host");
assert.match(playwrightConfig, /const port = 3100;/, "Playwright config should keep the fixed local E2E port");
assert.match(playwrightConfig, /const baseURL = "http:\/\/" \+ host \+ ":" \+ port;/, "Playwright baseURL should be built from host and port");
assert.doesNotMatch(playwrightConfig, /\[http:\/\/|\]\(http:\/\//, "Playwright config must not contain Markdown-link URL pollution");
assert.doesNotMatch(playwrightConfig, /http:\/\/127\.0\.0\.1:3100/, "Playwright config source should not contain the full local URL literal");
assert.match(playwrightConfig, /\.next\/standalone\/server\.js/, "Playwright webServer should use the standalone production server");
assert.match(playwrightConfig, /cp -R \.next\/static \.next\/standalone\/\.next\/static/, "Playwright webServer should copy .next/static into the standalone runtime");
assert.match(playwrightConfig, /cp -R public \.next\/standalone\/public/, "Playwright webServer should copy public assets into the standalone runtime when present");
assert.match(playwrightConfig, /PORT=3100 HOSTNAME=127\.0\.0\.1 node \.next\/standalone\/server\.js/, "Playwright webServer should start the standalone server on the fixed host and port");
assert.doesNotMatch(playwrightConfig, /node -e/, "Playwright webServer should not use nested node -e JavaScript strings");
assert.doesNotMatch(playwrightConfig, /npm run build/, "Playwright webServer should not rebuild because the audit builds before E2E");
assert.doesNotMatch(playwrightConfig, /npm run start|next start/, "Playwright webServer should not use next start with output: standalone");
assert.match(playwrightConfig, /RUNWAYLAB_E2E/, "Playwright config should require RUNWAYLAB_E2E");
assert.match(playwrightConfig, /DATABASE_URL/, "Playwright config should require DATABASE_URL");
assert.doesNotMatch(playwrightConfig, /test\.skip/, "Playwright config must not skip missing E2E environment");

assert.match(e2eSpec, /assertIsolatedE2EEnvironment/, "E2E spec should guard seed and cleanup with isolated database checks");
assert.match(e2eSpec, /RUNWAYLAB_E2E/, "E2E spec should require RUNWAYLAB_E2E=1");
assert.match(e2eSpec, /runwaylab_e2e/, "E2E spec should recognize the isolated test database name");
assert.match(e2eSpec, /e2e-owner@runwaylab\.test/, "E2E spec should use the dedicated owner account");
assert.match(e2eSpec, /e2e-admin@runwaylab\.test/, "E2E spec should use the dedicated admin account");
assert.match(e2eSpec, /e2e-outsider@runwaylab\.test/, "E2E spec should use the dedicated outsider account");
assert.match(e2eSpec, /await login\(ownerPage, ownerEmail\)/, "E2E should perform real owner login through the browser page");
assert.match(e2eSpec, /await ownerPage\.goto\("\/start"\)/, "E2E should create the intake from the /start browser context");
assert.match(e2eSpec, /\/api\/start-projects/, "E2E should create a real ProjectIntake through the application API");
assert.match(e2eSpec, /\/api\/start-projects\/\$\{intakeId\}\/submit/, "E2E should submit the intake for review");
assert.match(e2eSpec, /ProjectIntakeStatus\.SUBMITTED/, "E2E should assert ProjectIntake database status");
assert.match(e2eSpec, /\/api\/admin\/project-intakes\/\$\{intakeId\}\/review/, "E2E should perform admin ACCEPTED review");
assert.match(e2eSpec, /decision:\s*"ACCEPTED"/, "E2E should cover ACCEPTED review");
assert.match(e2eSpec, /\/api\/admin\/project-intakes\/\$\{intakeId\}\/convert/, "E2E should convert the intake into a formal project");
assert.match(e2eSpec, /CollaborationProjectVisibility\.PRIVATE/, "E2E should assert PRIVATE visibility");
assert.match(e2eSpec, /linkedCollaborationProjectId/, "E2E should assert linkedCollaborationProjectId");
assert.match(e2eSpec, /CollaborationProjectEventType\.PROJECT_CREATED/, "E2E should assert PROJECT_CREATED event");
assert.match(e2eSpec, /sanitizeRequestBody/, "E2E request helper should include sanitized request bodies in failure diagnostics");
assert.match(e2eSpec, /response=\$\{JSON\.stringify\(response\.json \?\? response\.text\)\}/, "E2E request helper should include response JSON or text in failure diagnostics");
assert.match(e2eSpec, /const userActionTitle = `E2E user \$\{actionSuffix\}`/, "E2E should keep create-action titles within the route contract");
assert.doesNotMatch(e2eSpec, /title: `\$\{titlePrefix\} .* action/, "E2E create-action titles should not exceed the 40 character route limit");
assert.match(e2eSpec, /await ownerPage\.goto\("\/me\/projects"\)/, "E2E should browse /me/projects for de-duplication");
assert.match(e2eSpec, /article:has\(a\[href="\$\{projectHrefValue\}"\]\)/, "E2E should count converted project entities by stable project href");
assert.match(e2eSpec, /article:has\(a\[href="\/me\/start-projects\/\$\{intakeId\}"\]\)/, "E2E should assert the converted intake card is hidden by stable intake href");
assert.doesNotMatch(e2eSpec, /bodyText\.match\(new RegExp\(flowProjectTitle/, "E2E should not count whole-page title text as project entities");
assert.match(e2eSpec, /CollaborationProjectActionStatus\.WAITING_PLATFORM_CONFIRMATION/, "E2E should cover user result waiting for platform confirmation");
assert.match(e2eSpec, /expectAdminListContains\("WAITING_PLATFORM", true\)/, "E2E should browse the waiting platform filter");
assert.match(e2eSpec, /expectAdminListContains\("WAITING_USER", true\)/, "E2E should browse the waiting user filter");
assert.match(e2eSpec, /expectAdminListContains\("WAITING_NEXT", true\)/, "E2E should browse the waiting next-step filter");
assert.match(e2eSpec, /expectAdminListContains\(null, false\)/, "E2E should assert USER ACTIVE is excluded from default pending");
assert.match(e2eSpec, /cancellationEventCountBefore/, "E2E should count cancellation events before cancelling an action");
assert.match(e2eSpec, /cancelledAction\.cancellationReason/, "E2E should assert cancellation reason in the database, not as a current-action UI contract");
assert.match(e2eSpec, /expectAdminListContains\(null, true\)/, "E2E should assert default pending includes projects waiting for the next platform step");
assert.match(e2eSpec, /expectAdminListContains\("WAITING_USER", false\)/, "E2E should assert cancelled actions leave the waiting-user queue");
assert.match(e2eSpec, /input\[maxlength="40"\]/, "E2E should assert the admin detail has returned to next-step scheduling UI");
assert.doesNotMatch(e2eSpec, /expect\(detailText\)\.toContain\("Cancelling this E2E action"\)/, "E2E should not require cancelled action reasons to remain visible in current-action UI");
assert.match(e2eSpec, /outsider cannot read owner private project/, "E2E should cover outsider private project access");
assert.match(e2eSpec, /\/admin\/projects/, "E2E should cover outsider admin project management access");
assert.match(e2eSpec, /adminApiAttempt\.status\)\.toBe\(403\)/, "E2E should assert outsider admin API access is forbidden");
assert.match(e2eSpec, /not\.toContain\(ownerEmail\)/, "E2E should assert outsider responses do not leak owner identity");
assert.match(e2eSpec, /Promise\.all/, "E2E should create concurrent current actions");
assert.match(e2eSpec, /expect\(rejected\[0\]\.status\)\.toBe\(409\)/, "E2E should assert the losing concurrent create follows the 409 route contract");
assert.match(e2eSpec, /expect\(successful\[0\]\.json\.action\.responsibility\)\.toBe\(CollaborationProjectActionResponsibility\.PLATFORM\)/, "E2E should assert the winning concurrent action payload persisted correctly");
assert.match(e2eSpec, /countOpenActions/, "E2E should assert open action count");
assert.match(e2eSpec, /CollaborationProjectEventType\.ACTION_CREATED/, "E2E should assert ACTION_CREATED events");
assert.match(e2eSpec, /NotificationType\.REQUEST_HANDLED/, "E2E should assert notifications are not duplicated");
assert.doesNotMatch(e2eSpec, /manual-step/, "E2E spec must not use manual-step annotations as coverage");
assert.doesNotMatch(e2eSpec, /test\.skip/, "E2E spec must fail instead of skipping missing environment");

console.log("operational acceptance E2E coverage tests passed");
