import * as assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const report = readFileSync("RUNWAYLAB_V2_0B_5_SIMPLE_PROJECT_EXPERIENCE_REPORT.md", "utf8");
const packageJsonText = readFileSync("package.json", "utf8");
const playwrightConfig = readFileSync("playwright.config.mjs", "utf8");
const e2eSpec = readFileSync("e2e/operational-acceptance.spec.mjs", "utf8");
const packageJson = JSON.parse(packageJsonText) as {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
};

assert.match(report, /V2\.0B\.5/, "report should document the V2.0B.5 acceptance scope");
assert.match(report, /自动创建 PRIVATE `CollaborationProject`/, "report should document automatic private project creation");
assert.match(report, /createInitialPrivateProjectActionForIntake/, "report should document deterministic first action creation");
assert.match(report, /不作为普通用户默认流程/, "report should state admin review/convert is no longer the default user flow");
assert.match(report, /scripts\/\*-tests\.ts[\s\S]*Passed scripts: 75/, "report should keep the 75 script suites result");

assert.ok(packageJson.devDependencies?.["@playwright/test"], "@playwright/test must be a devDependency");
assert.equal(packageJson.dependencies?.["@playwright/test"], undefined, "@playwright/test must not be a runtime dependency");
assert.match(playwrightConfig, /const host = "127\.0\.0\.1";/, "Playwright config should keep the fixed local E2E host");
assert.match(playwrightConfig, /const port = 3100;/, "Playwright config should keep the fixed local E2E port");
assert.match(playwrightConfig, /const baseURL = "http:\/\/" \+ host \+ ":" \+ port;/, "Playwright baseURL should be built from host and port");
assert.doesNotMatch(playwrightConfig, /\[http:\/\/|\]\(http:\/\//, "Playwright config must not contain Markdown-link URL pollution");
assert.doesNotMatch(playwrightConfig, /http:\/\/127\.0\.0\.1:3100/, "Playwright config source should not contain the full local URL literal");
assert.match(playwrightConfig, /\.next\/standalone\/server\.js/, "Playwright webServer should use the standalone production server");
assert.match(playwrightConfig, /PORT=3100 HOSTNAME=127\.0\.0\.1 node \.next\/standalone\/server\.js/, "Playwright webServer should start the standalone server on the fixed host and port");
assert.doesNotMatch(playwrightConfig, /node -e/, "Playwright webServer should not use nested node -e JavaScript strings");
assert.doesNotMatch(playwrightConfig, /npm run build/, "Playwright webServer should not rebuild because the audit builds before E2E");
assert.doesNotMatch(playwrightConfig, /npm run start|next start/, "Playwright webServer should not use next start with output: standalone");
assert.match(playwrightConfig, /RUNWAYLAB_E2E/, "Playwright config should require RUNWAYLAB_E2E");
assert.match(playwrightConfig, /DATABASE_URL/, "Playwright config should require DATABASE_URL");
assert.doesNotMatch(playwrightConfig, /test\.skip/, "Playwright config must not skip missing E2E environment");

assert.match(e2eSpec, /V2\.0B\.5 simple project experience acceptance/, "E2E spec should target the V2.0B.5 simple project flow");
assert.match(e2eSpec, /contractLimits/, "E2E spec should define local test-data contract limits");
assert.match(e2eSpec, /safeProjectTitle/, "E2E spec should generate short project titles through a helper");
assert.match(e2eSpec, /safeActionTitle/, "E2E spec should generate short action titles through a helper");
assert.match(e2eSpec, /preflightRequestBody/, "E2E spec should preflight request bodies before API calls");
assert.match(e2eSpec, /contractLimits\.safeProjectTitle/, "E2E project titles should stay below a safety limit, not the API maximum");
assert.match(e2eSpec, /contractLimits\.safeActionTitle/, "E2E action titles should stay below a safety limit, not the API maximum");
assert.doesNotMatch(e2eSpec, /const .*ProjectTitle = `[^`]*\$\{runId\}/, "E2E project titles must not include the full dynamic runId");
assert.doesNotMatch(e2eSpec, /projectTitle: `[^`]*\$\{Date\.now\(\)\}/, "E2E projectTitle payloads must not concatenate a raw timestamp");
assert.match(e2eSpec, /assertIsolatedE2EEnvironment/, "E2E spec should guard seed and cleanup with isolated database checks");
assert.match(e2eSpec, /RUNWAYLAB_E2E/, "E2E spec should require RUNWAYLAB_E2E=1");
assert.match(e2eSpec, /DATABASE_URL/, "E2E spec should require DATABASE_URL");
assert.match(e2eSpec, /runwaylab_e2e/, "E2E spec should recognize the isolated test database name");
assert.match(e2eSpec, /e2e-owner@runwaylab\.test/, "E2E spec should use the dedicated owner account");
assert.match(e2eSpec, /e2e-admin@runwaylab\.test/, "E2E spec should use the dedicated admin account");
assert.match(e2eSpec, /e2e-outsider@runwaylab\.test/, "E2E spec should use the dedicated outsider account");
assert.match(e2eSpec, /await login\(ownerPage, ownerEmail\)/, "E2E should perform real owner login through the browser page");
assert.match(e2eSpec, /await ownerPage\.goto\("\/start"\)/, "E2E should create the intake from the /start browser context");
assert.match(e2eSpec, /\/api\/start-projects/, "E2E should create a real ProjectIntake through the application API");
assert.match(e2eSpec, /\/api\/start-projects\/\$\{intakeId\}\/submit/, "E2E should launch the intake through the real submit endpoint");
assert.match(e2eSpec, /ProjectIntakeStatus\.ACCEPTED/, "E2E should assert the V2.0B.5 completed intake state");
assert.match(e2eSpec, /reviewedById\)\.toBeNull/, "E2E should assert no admin review is required for the default flow");
assert.doesNotMatch(e2eSpec, /\/api\/admin\/project-intakes\/\$\{intakeId\}\/review/, "E2E should not restore the old admin review flow");
assert.doesNotMatch(e2eSpec, /\/api\/admin\/project-intakes\/\$\{intakeId\}\/convert/, "E2E should not restore the old admin conversion flow");
assert.match(e2eSpec, /CollaborationProjectVisibility\.PRIVATE/, "E2E should assert PRIVATE visibility");
assert.match(e2eSpec, /linkedCollaborationProjectId/, "E2E should assert intake to project linkage");
assert.match(e2eSpec, /CollaborationProjectEventType\.PROJECT_CREATED/, "E2E should assert PROJECT_CREATED event");
assert.match(e2eSpec, /CollaborationProjectEventType\.ACTION_CREATED/, "E2E should assert ACTION_CREATED event");
assert.match(e2eSpec, /CollaborationProjectActionType\.DESIGN_CLARIFICATION/, "E2E should assert deterministic first action type");
assert.match(e2eSpec, /CollaborationProjectActionResponsibility\.USER/, "E2E should assert deterministic first action responsibility");
assert.match(e2eSpec, /countOpenActions/, "E2E should assert unfinished action counts");
assert.match(e2eSpec, /idempotent/, "E2E should assert repeated intake launch is idempotent");
assert.match(e2eSpec, /duplicate project, action, event, or notification/, "E2E should cover duplicate launch deduplication");
assert.match(e2eSpec, /NotificationType\.REQUEST_HANDLED/, "E2E should assert notifications are not duplicated");
assert.match(e2eSpec, /sanitizeRequestBody/, "E2E request helper should include sanitized request bodies in failure diagnostics");
assert.match(e2eSpec, /response=\$\{JSON\.stringify\(response\.json \?\? response\.text\)\}/, "E2E request helper should include response JSON or text in failure diagnostics");
assert.match(e2eSpec, /await ownerPage\.goto\("\/me\/projects"\)/, "E2E should browse /me/projects");
assert.match(e2eSpec, /article:has\(a\[href="\$\{projectHrefValue\}"\]\)/, "E2E should count project entities by stable project href");
assert.match(e2eSpec, /article:has\(a\[href="\/me\/start-projects\/\$\{intakeId\}"\]\)/, "E2E should assert the converted intake card is hidden by stable intake href");
assert.doesNotMatch(e2eSpec, /bodyText\.match\(new RegExp\(flowProjectTitle/, "E2E should not count whole-page title text as project entities");
assert.match(e2eSpec, /not\.toContainText\("正式项目"\)/, "E2E should assert internal project wording is hidden from /me/projects");
assert.match(e2eSpec, /not\.toContainText\("启动草稿"\)/, "E2E should assert old draft wording is hidden from /me/projects");
assert.match(e2eSpec, /not\.toContainText\("等待平台评估"\)/, "E2E should assert old review wording is hidden from /me/projects");
assert.match(e2eSpec, /toContainText\("现在要做"\)/, "E2E should assert USER ACTIVE human-facing project detail copy");
assert.match(e2eSpec, /not\.toContainText\("USER"\)/, "E2E should assert USER enum is hidden from owner project detail");
assert.match(e2eSpec, /not\.toContainText\("PLATFORM"\)/, "E2E should assert PLATFORM enum is hidden from owner project detail");
assert.match(e2eSpec, /CollaborationProjectActionStatus\.WAITING_PLATFORM_CONFIRMATION/, "E2E should cover user result waiting for platform confirmation");
assert.match(e2eSpec, /USER_RESULT_SUBMITTED/, "E2E should assert user result event creation");
assert.match(e2eSpec, /toContainText\("已收到"\)/, "E2E should assert received user-facing copy");
assert.match(e2eSpec, /toContainText\("我们正在处理"\)/, "E2E should assert platform-active user-facing copy");
assert.match(e2eSpec, /outsider cannot read owner project/, "E2E should cover outsider private project access");
assert.match(e2eSpec, /adminApiAttempt\.status\)\.toBe\(403\)/, "E2E should assert outsider admin API access is forbidden");
assert.match(e2eSpec, /submitAttempt\.status\)\.toBe\(404\)/, "E2E should assert outsider action submission does not leak private project details");
assert.match(e2eSpec, /\/admin\/projects/, "E2E should cover outsider admin project management access");
assert.match(e2eSpec, /Promise\.all/, "E2E should cover concurrent duplicate launch requests");
assert.match(e2eSpec, /document\.documentElement\.scrollWidth/, "E2E should include real browser responsive overflow checks");
assert.match(e2eSpec, /width: 375, height: 812/, "E2E should include the 375x812 responsive smoke viewport");
assert.match(e2eSpec, /width: 390, height: 844/, "E2E should include the 390x844 responsive smoke viewport");
assert.match(e2eSpec, /width: 430, height: 932/, "E2E should include the 430x932 responsive smoke viewport");
assert.match(e2eSpec, /width: 1440, height: 900/, "E2E should include the 1440x900 responsive smoke viewport");
assert.doesNotMatch(e2eSpec, /manual-step/, "E2E spec must not use manual-step annotations as coverage");
assert.doesNotMatch(e2eSpec, /test\.skip/, "E2E spec must fail instead of skipping missing environment");

console.log("operational acceptance E2E coverage tests passed");
