import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const service = readFileSync("src/lib/start-projects.ts", "utf8");
const actionService = readFileSync("src/lib/private-project-actions.ts", "utf8");
const experience = readFileSync("src/lib/private-collaboration-projects.ts", "utf8");
const submitRoute = readFileSync("src/app/api/start-projects/[id]/submit/route.ts", "utf8");
const meProjects = readFileSync("src/app/me/projects/page.tsx", "utf8");
const projectDetail = readFileSync("src/app/me/projects/collaboration/[id]/page.tsx", "utf8");
const actionCard = readFileSync("src/components/projects/PrivateProjectActionCard.tsx", "utf8");
const startDetails = readFileSync("src/components/start/ProjectIntakeDetailsFlow.tsx", "utf8");

assert.match(service, /function initialActionForProjectIntake/, "first action should be generated by deterministic rules");
assert.match(service, /title:\s*"完善产品需求"/, "idea projects should get a human first action title");
assert.match(service, /title:\s*"确认开发目标"/, "design-source projects should get a deterministic first action title");
assert.match(service, /createInitialPrivateProjectActionForIntake\(tx/, "launch should create the first action inside the submit transaction");
assert.match(service, /visibility:\s*CollaborationProjectVisibility\.PRIVATE/, "auto-created projects must remain private");
assert.match(service, /linkedCollaborationProjectId:\s*project\.id/, "launch should link the intake to the created project");
assert.match(service, /convertedAt:\s*now/, "launch should preserve conversion audit fields");
assert.match(service, /if \(current\.linkedCollaborationProjectId\) \{[\s\S]*idempotent:\s*true/, "duplicate launch should return the existing project");
assert.match(actionService, /status:\s*\{\s*in:\s*\[\.\.\.OPEN_PRIVATE_PROJECT_ACTION_STATUSES\]\s*\}/, "first action creation must check for an existing unfinished action");
assert.match(actionService, /CollaborationProjectEventType\.ACTION_CREATED/, "first action creation should write an action-created event");
assert.match(actionService, /createPrivateProjectNotification/, "first action creation should reuse notification de-duplication");
assert.match(submitRoute, /href:\s*success\.project \? privateCollaborationProjectHref\(success\.project\.id\)/, "submit route should send users straight to the project workbench");

assert.match(experience, /export function getProjectExperienceStage/, "UI stage mapping should be centralized");
assert.match(experience, /stage:\s*"IDEA"|stage,\s*headline/, "experience helper should expose a simple stage");
assert.match(experience, /headline:\s*"现在要做"/, "USER active actions should become a human current-task headline");
assert.match(experience, /headline:\s*"已收到"/, "waiting confirmation should become a human received state");
assert.match(experience, /headline:\s*"我们正在处理"/, "platform active actions should become a human processing state");
assert.match(experience, /headline:\s*"正在准备下一步"/, "projects without an unfinished action should avoid next-action jargon");

assert.match(meProjects, /<h1[^>]*>我的项目<\/h1>/, "project list should use the simple user-facing title");
assert.match(meProjects, /从想法到第一件真实产品/, "project list should explain the journey in plain language");
assert.match(meProjects, /新建项目/, "project list should keep one clear creation entry");
assert.match(meProjects, /StageProgress/, "project list should show the four-stage progress UI");
assert.match(meProjects, /继续/, "project cards should expose one primary continue action");
assert.doesNotMatch(meProjects, /项目数|启动草稿数|正式项目数|内部模型数量|查看草稿|项目详情|等待平台安排下一步/, "project list should not expose old operational labels");

assert.match(projectDetail, /StageProgress/, "project detail should show lightweight stage progress");
assert.match(projectDetail, /PrivateProjectActionCard/, "project detail should keep the real user action workflow");
assert.doesNotMatch(projectDetail, /当前动作|当前行动|正式项目|原始启动|责任方|事件模型/, "project detail should avoid internal project-management language");
assert.match(actionCard, /现在要做/, "USER active detail state should say what to do now");
assert.match(actionCard, /已收到/, "submitted user result should show a received state");
assert.match(actionCard, /我们正在处理/, "platform-owned action should be hidden behind a processing state");
assert.match(actionCard, /继续[\s\S]*完成/, "user action should be a continue-first flow");
assert.doesNotMatch(actionCard, />USER<|>PLATFORM<|责任方|当前行动/, "action card should not render internal action vocabulary");

assert.match(startDetails, /确认启动项目？/, "start details should launch instead of asking for a review");
assert.match(startDetails, /你不用等待人工评估/, "start details should explain the simplified launch");
assert.doesNotMatch(startDetails, /确认提交平台评估？|正式项目已建立/, "start details should remove old review/conversion copy");
assert.match(`${meProjects}\n${projectDetail}\n${actionCard}`, /min-h-11|min-h-12/, "primary controls should keep mobile-friendly tap targets");
assert.match(`${meProjects}\n${projectDetail}`, /px-4/, "pages should keep mobile padding");

console.log("simple project experience tests passed");
